version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    networks:
      - tracker_network
    # volumes: 
      # - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    command: redis-server --requirepass password
    # volumes:
      # - redis_data:/data
    networks:
      - tracker_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9091:9091"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  tracker_network:
    driver: bridge

# volumes:
#   postgres_data:
#   redis_data:
